title: Spencer Bull
description: Software Engineer • AI/ML • Robotics
baseurl: ""
url: "https://spencerbull.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Defaults
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Spencer Bull"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
